insert into agente.sinonimos (termo, canonico) values
  -- abreviações do ERP
  ('RET',            'RETENTOR'),
  ('DIANT',          'DIANTEIRO'),
  ('TRAS',           'TRASEIRO'),
  ('TRAZ',           'TRASEIRO'),
  ('EMB',            'EMBREAGEM'),
  ('TRANS',          'TRANSMISSAO'),
  ('VIRAB',          'VIRABREQUIM'),
  ('CROM',           'CROMADO'),
  ('ESQ',            'ESQUERDO'),
  ('DIR',            'DIREITO'),
  ('LAT',            'LATERAL'),
  ('PRIM',           'PRIMARIA'),
  ('EXT',            'EXTERNA'),
  ('COMB',           'COMBUSTIVEL'),
  ('JG',             'JOGO'),
  ('MANG',           'MANGUEIRA'),
  ('MOD',            'MODELO'),
  ('ORIG',           'ORIGINAL'),
  ('PTO',            'PRETO'),
  ('COMP',           'COMPETICAO'),
  ('COMPET',         'COMPETICAO'),
  -- vocabulário do cliente
  ('KIT RELACAO',    'COROA TRANS'),
  ('RELACAO',        'COROA TRANS'),
  ('COROA E PINHAO', 'COROA TRANS'),
  ('TITAM',          'TITAN'),
  ('BIZZ',           'BIZ'),
  ('FAM',            'FAN'),
  ('BROSS',          'BROS'),
  ('FASER',          'FAZER'),
  ('PASTILHA',       'PASTILHA FREIO'),
  ('LONA',           'LONA FREIO'),
  ('VELA DE IGNICAO','VELA'),
  ('CAMARA DE AR',   'CAMARA'),
  ('OLHO DE GATO',   'OLHO GATO'),
  ('PISCA',          'PISCA'),
  ('BENGALA',        'BENGALA'),
  ('COXIM',          'COXIM')
on conflict (termo) do update set canonico = excluded.canonico;
